import type { Manifest } from './schema';
import type { ResolvedTree } from './resolve';

const HEADER = (manifest: Manifest) =>
  `// AUTO-GENERATED by \`bun run ds:apply\` from design-systems/${manifest.name}@${manifest.version}.\n// Do not edit by hand: change the tokens and re-run the script.\n`;

export function generateThemes(
  manifest: Manifest,
  light: ResolvedTree,
  dark: ResolvedTree,
): string {
  const json = (value: ResolvedTree) => JSON.stringify(value, null, 2);
  return `${HEADER(manifest)}
export const light = ${json(light)};

export type Theme = typeof light;

export const dark: Theme = ${json(dark)};

export const themes = { light, dark };
`;
}

export function generateFonts(manifest: Manifest, fontsImportDir: string): string {
  const entries = manifest.fonts
    .map((font) => {
      const fileName = font.file.split('/').pop() ?? font.file;
      return `  '${font.family}': require('${fontsImportDir}/${fileName}'),`;
    })
    .join('\n');
  return `${HEADER(manifest)}
import type { FontSource } from 'expo-font';

export const fonts: Record<string, FontSource> = {
${entries}
};
`;
}

export function generateMeta(manifest: Manifest): string {
  return `${JSON.stringify({ name: manifest.name, version: manifest.version }, null, 2)}\n`;
}

const IDENTIFIER = /^[A-Za-z_$][A-Za-z0-9_$]*$/;
const key = (name: string) => (IDENTIFIER.test(name) ? name : JSON.stringify(name));
const access = (name: string) => (IDENTIFIER.test(name) ? `.${name}` : `[${JSON.stringify(name)}]`);

function keysOf(tree: ResolvedTree, group: string, sub?: string): string[] {
  const node = tree[group];
  const target =
    sub !== undefined && node !== undefined && typeof node === 'object' ? node[sub] : node;
  return target !== undefined && typeof target === 'object' ? Object.keys(target) : [];
}

function variantMap(keys: string[], render: (k: string) => string): string {
  return `{\n${keys.map((k) => `    ${key(k)}: ${render(k)},`).join('\n')}\n  }`;
}

export function generateStyleProps(manifest: Manifest, light: ResolvedTree): string {
  const space = keysOf(light, 'space');
  const spaceProp = (cssProp: string) =>
    variantMap(space, (k) => `{ ${cssProp}: theme.space${access(k)} }`);

  return `${HEADER(manifest)}
import type { Theme } from './themes';

export const textStyleProps = (theme: Theme) => ({
  variant: ${variantMap(keysOf(light, 'typography'), (k) => `theme.typography${access(k)}`)},
  color: ${variantMap(keysOf(light, 'colors', 'text'), (k) => `{ color: theme.colors.text${access(k)} }`)},
  fontSize: ${variantMap(keysOf(light, 'fontSize'), (k) => `{ fontSize: theme.fontSize${access(k)} }`)},
  lineHeight: ${variantMap(keysOf(light, 'lineHeight'), (k) => `{ lineHeight: theme.lineHeight${access(k)} }`)},
  weight: ${variantMap(keysOf(light, 'fontFamily'), (k) => `{ fontFamily: theme.fontFamily${access(k)} }`)},
});

export const boxStyleProps = (theme: Theme) => ({
  bg: ${variantMap(keysOf(light, 'colors', 'bg'), (k) => `{ backgroundColor: theme.colors.bg${access(k)} }`)},
  radius: ${variantMap(keysOf(light, 'radius'), (k) => `{ borderRadius: theme.radius${access(k)} }`)},
  padding: ${spaceProp('padding')},
  paddingX: ${spaceProp('paddingHorizontal')},
  paddingY: ${spaceProp('paddingVertical')},
  margin: ${spaceProp('margin')},
  marginX: ${spaceProp('marginHorizontal')},
  marginY: ${spaceProp('marginVertical')},
  gap: ${spaceProp('gap')},
});
`;
}
